config/routes.rb
edit of root from pages#home to celebrities#index
=> edit of root

app/controllers/bookings_controller.rb, app/controllers/celebrities_controller.rb, test/controllers/booking_controller_test.rb, test/controllers/celebrities_controller_test.rb
=> creation controller

app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, config/initializers/devise.rb
=> views added

app/controllers/celebrities_controller.rb, app/views/celebrities/index.html.erb, app/views/pages/home.html.erb, config/routes.rb
edit of routes & first code for celebrities index.html.erb
=> routes edit & first html code

app/assets/stylesheets/pages/_index.scss, app/views/celebrities/index.html.erb
start of design for celebrities > index.html.erb
=> start of celebrities index html creation

app/views/bookings/_form.html.erb, app/views/celebrities/index.html.erb
reusable card in celebrities index and form partial for bookings
=> Card and form

app/views/celebrities/index.html.erb, db/migrate/20241119104402_add_rating.rb, db/schema.rb, db/seeds.rb
Seed is now created
We added a rating column to the celebrities' table
=> seed and rating column added to database

app/controllers/bookings_controller.rb, app/views/bookings/_form.html.erb, app/views/bookings/new.html.erb, config/routes.rb, db/migrate/20241119123652_add_celebrity_word.rb, db/schema.rb
1. Word/description from celebrity column created, 
2. New view form working
3. Routes modified: nested bookings inside celebrity so that the new_form would add a booking linking the celebrity with celebrity_id.
=> word/description from celebrity column created, new view form working

app/assets/stylesheets/application.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_navbar.scss, app/views/shared/_navbar.html.erb
- creation of color variables
- creation of font variables
- edit of the navbar (font, color, logo)
=> navbar edit

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_index_booking.scss, app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/bookings/_form.html.erb, app/views/bookings/index.html.erb
creation de la view booking index avec l'historique des resas
il manque les photos
=> creation de la view booking index avec l'historique des resas

app/assets/stylesheets/config/_fonts.scss, app/views/celebrities/index.html.erb
=> Index icon artists

app/assets/stylesheets/pages/_index.scss, app/views/celebrities/index.html.erb
- edit of search bar
- improvement of icon category
=> add of search bar & icons

app/views/celebrities/index.html.erb
=> Celebrities index creation

app/views/celebrities/show.html.erb, db/migrate/20241120103631_add_images_to_celebrities.rb, db/schema.rb, db/seeds.rb
=> new seed with more elements

app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/bookings/index.html.erb, config/routes.rb, db/migrate/20241120131926_add_bookings_status.rb, db/schema.rb
Feature accept or refuse booking
=> new feature accept or refuse booking

app/controllers/bookings_controller.rb, app/controllers/pages_controller.rb, app/models/celebrity.rb, app/models/user.rb, app/views/bookings/_form.html.erb, app/views/bookings/index.html.erb, app/views/layouts/application.html.erb, app/views/pages/dashboard.html.erb, config/routes.rb
1. Nouvelle route "Dashboard" -> pour l'utiliser "dashboard_path"
2. View dashboard avec demandes du current_user
3. Demande de réservation qui affiche bien seulement la demande faite à la célébrité en question
4. Activités dans le formulaire de réservation pour affichage dans le dashboard et dans les demandes de réservation
=> dashboard added, booking requests, activities in form

app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/celebrities_controller.rb, app/views/bookings/_form.html.erb, app/views/bookings/index.html.erb, app/views/celebrities/index.html.erb, app/views/celebrities/new.html.erb, app/views/celebrities/show.html.erb, app/views/pages/dashboard.html.erb, app/views/shared/_navbar.html.erb
- harmonisation police
- harmonisation boutons
=> Final front edits

app/controllers/bookings_controller.rb, app/models/user.rb, app/views/celebrities/index.html.erb, db/seeds.rb
- ajout des modifs pour MLP
- ajout de la page personnalisée pour les reservations
=> edits marine

app/views/celebrities/index.html.erb
- ajout icons de couleur sur l'index celebrités
=> add of icons

app/controllers/celebrities_controller.rb, app/views/celebrities/new.html.erb, app/views/celebrities/show.html.erb
ajouté description au manager de la star et changer la route du post de louer
=> derniers changements
